-- =====================================================================
-- V1: Schema inicial - estructura, funciones, triggers e índices.
-- Los seeds de catálogos van en V2.
-- =====================================================================

CREATE SCHEMA IF NOT EXISTS clinica;
SET search_path TO clinica;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE OR REPLACE FUNCTION uuid_generate_v7()
RETURNS UUID AS $$
BEGIN
    RETURN encode(
        set_bit(
            set_bit(
                overlay(
                    uuid_send(gen_random_uuid())
                    PLACING substring(int8send(floor(extract(epoch from clock_timestamp()) * 1000)::bigint) from 3)
                    FROM 1 FOR 6
                ),
                52, 1
            ),
            53, 1
        ),
        'hex'
    )::uuid;
END;
$$ LANGUAGE plpgsql VOLATILE;

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TYPE estado_cita         AS ENUM ('PROGRAMADA','CONFIRMADA','EN_CURSO','ATENDIDA','CANCELADA','NO_ASISTIO');
CREATE TYPE estado_hallazgo     AS ENUM ('EXISTENTE','REQUERIDO','REALIZADO');
CREATE TYPE estado_plan         AS ENUM ('PROPUESTO','ACEPTADO','RECHAZADO','EN_EJECUCION','COMPLETADO','PARCIAL');
CREATE TYPE estado_detalle_plan AS ENUM ('PENDIENTE','EJECUTADO','OMITIDO','REPROGRAMADO');
CREATE TYPE tipo_habito         AS ENUM ('TABACO','ALCOHOL','DROGAS','OTRO');
CREATE TYPE frecuencia_habito   AS ENUM ('NUNCA','OCASIONAL','FRECUENTE','DIARIO','EX_CONSUMIDOR');

-- ===== CATÁLOGOS =====

CREATE TABLE sexo (
    id SMALLINT PRIMARY KEY,
    codigo VARCHAR(1) NOT NULL,
    descripcion VARCHAR(20) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_sexo_codigo UNIQUE (codigo)
);

CREATE TABLE estado_civil (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(20) NOT NULL,
    descripcion VARCHAR(50) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_estado_civil_codigo UNIQUE (codigo)
);

CREATE TABLE grado_instruccion (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(30) NOT NULL,
    descripcion VARCHAR(80) NOT NULL,
    orden SMALLINT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_grado_codigo UNIQUE (codigo)
);

CREATE TABLE tipo_documento (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(10) NOT NULL,
    descripcion VARCHAR(50) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_tipo_doc_codigo UNIQUE (codigo)
);

CREATE TABLE parentesco (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(20) NOT NULL,
    descripcion VARCHAR(50) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_parentesco_codigo UNIQUE (codigo)
);

CREATE TABLE cara_dental (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(20) NOT NULL,
    descripcion VARCHAR(50) NOT NULL,
    abreviatura VARCHAR(3) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_cara_codigo UNIQUE (codigo)
);

CREATE TABLE condicion_dental (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(30) NOT NULL,
    descripcion VARCHAR(100) NOT NULL,
    color_hex VARCHAR(7) NOT NULL DEFAULT '#000000',
    requiere_cara BOOLEAN NOT NULL DEFAULT TRUE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_condicion_codigo UNIQUE (codigo)
);

CREATE TABLE pieza_dental (
    id SMALLINT PRIMARY KEY,
    cuadrante SMALLINT NOT NULL,
    posicion SMALLINT NOT NULL,
    nombre VARCHAR(40) NOT NULL,
    is_deciduo BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT ck_pieza_cuadrante CHECK (cuadrante BETWEEN 0 AND 8),
    CONSTRAINT ck_pieza_posicion  CHECK (posicion  BETWEEN 0 AND 8)
);

CREATE TABLE procedimiento (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v7(),
    codigo VARCHAR(20) NOT NULL,
    nombre VARCHAR(150) NOT NULL,
    descripcion TEXT NOT NULL DEFAULT '',
    precio_base NUMERIC(10,2) NOT NULL DEFAULT 0,
    duracion_min SMALLINT NOT NULL DEFAULT 30,
    requiere_pieza BOOLEAN NOT NULL DEFAULT TRUE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ,
    CONSTRAINT uq_procedimiento_codigo UNIQUE (codigo),
    CONSTRAINT ck_procedimiento_precio CHECK (precio_base >= 0)
);
CREATE TRIGGER trg_procedimiento_updated BEFORE UPDATE ON procedimiento
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ===== TABLAS TRANSACCIONALES =====

CREATE TABLE persona (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v7(),
    tipo_documento_id SMALLINT NOT NULL,
    numero_documento VARCHAR(20) NOT NULL,
    nombres VARCHAR(100) NOT NULL,
    apellido_paterno VARCHAR(100) NOT NULL,
    apellido_materno VARCHAR(100) NOT NULL DEFAULT '',
    fecha_nacimiento DATE NOT NULL,
    sexo_id SMALLINT NOT NULL,
    celular VARCHAR(20) NOT NULL DEFAULT '',
    email VARCHAR(120) NOT NULL DEFAULT '',
    direccion VARCHAR(255) NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ,
    CONSTRAINT fk_persona_tipo_doc FOREIGN KEY (tipo_documento_id) REFERENCES tipo_documento(id),
    CONSTRAINT fk_persona_sexo     FOREIGN KEY (sexo_id) REFERENCES sexo(id),
    CONSTRAINT ck_persona_email    CHECK (email = '' OR email LIKE '%_@_%._%')
);
CREATE UNIQUE INDEX uq_persona_documento_active ON persona (tipo_documento_id, numero_documento) WHERE deleted_at IS NULL;
CREATE INDEX idx_persona_apellidos_active ON persona (apellido_paterno, apellido_materno) WHERE deleted_at IS NULL;
CREATE TRIGGER trg_persona_updated BEFORE UPDATE ON persona
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE paciente (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v7(),
    persona_id UUID NOT NULL,
    codigo_historia VARCHAR(20) NOT NULL,
    lugar_nacimiento VARCHAR(120) NOT NULL DEFAULT '',
    procedencia VARCHAR(120) NOT NULL DEFAULT '',
    viajes_ultimo_anio TEXT NOT NULL DEFAULT '',
    grado_instruccion_id SMALLINT NOT NULL,
    ocupacion VARCHAR(120) NOT NULL DEFAULT '',
    estado_civil_id SMALLINT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ,
    CONSTRAINT fk_paciente_persona FOREIGN KEY (persona_id) REFERENCES persona(id),
    CONSTRAINT fk_paciente_grado   FOREIGN KEY (grado_instruccion_id) REFERENCES grado_instruccion(id),
    CONSTRAINT fk_paciente_estciv  FOREIGN KEY (estado_civil_id) REFERENCES estado_civil(id)
);
CREATE UNIQUE INDEX uq_paciente_persona_active ON paciente (persona_id) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX uq_paciente_codigo_active ON paciente (codigo_historia) WHERE deleted_at IS NULL;
CREATE TRIGGER trg_paciente_updated BEFORE UPDATE ON paciente
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE contacto_emergencia (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v7(),
    paciente_id UUID NOT NULL,
    nombres_completos VARCHAR(200) NOT NULL,
    celular VARCHAR(20) NOT NULL,
    parentesco_id SMALLINT NOT NULL,
    is_apoderado BOOLEAN NOT NULL DEFAULT FALSE,
    prioridad SMALLINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ,
    CONSTRAINT fk_contacto_paciente FOREIGN KEY (paciente_id) REFERENCES paciente(id),
    CONSTRAINT fk_contacto_parentesco FOREIGN KEY (parentesco_id) REFERENCES parentesco(id),
    CONSTRAINT ck_contacto_prioridad CHECK (prioridad BETWEEN 1 AND 10)
);
CREATE INDEX idx_contacto_paciente_active ON contacto_emergencia (paciente_id) WHERE deleted_at IS NULL;
CREATE TRIGGER trg_contacto_updated BEFORE UPDATE ON contacto_emergencia
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE historia_clinica (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v7(),
    paciente_id UUID NOT NULL,
    fecha_apertura DATE NOT NULL DEFAULT CURRENT_DATE,
    odontologo_id UUID NOT NULL,
    observaciones_generales TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ,
    CONSTRAINT fk_historia_paciente FOREIGN KEY (paciente_id) REFERENCES paciente(id),
    CONSTRAINT fk_historia_odontologo FOREIGN KEY (odontologo_id) REFERENCES persona(id)
);
CREATE UNIQUE INDEX uq_historia_paciente_active ON historia_clinica (paciente_id) WHERE deleted_at IS NULL;
CREATE TRIGGER trg_historia_updated BEFORE UPDATE ON historia_clinica
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE cita (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v7(),
    paciente_id UUID NOT NULL,
    odontologo_id UUID NOT NULL,
    fecha_hora_inicio TIMESTAMPTZ NOT NULL,
    fecha_hora_fin TIMESTAMPTZ NOT NULL,
    estado estado_cita NOT NULL DEFAULT 'PROGRAMADA',
    motivo VARCHAR(255) NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ,
    CONSTRAINT fk_cita_paciente FOREIGN KEY (paciente_id) REFERENCES paciente(id),
    CONSTRAINT fk_cita_odontologo FOREIGN KEY (odontologo_id) REFERENCES persona(id),
    CONSTRAINT ck_cita_horario CHECK (fecha_hora_fin > fecha_hora_inicio)
);
CREATE INDEX idx_cita_fecha_active ON cita (fecha_hora_inicio) WHERE deleted_at IS NULL;
CREATE INDEX idx_cita_paciente_active ON cita (paciente_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_cita_estado_active ON cita (estado) WHERE deleted_at IS NULL;
CREATE TRIGGER trg_cita_updated BEFORE UPDATE ON cita
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE atencion (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v7(),
    cita_id UUID NOT NULL,
    historia_clinica_id UUID NOT NULL,
    odontologo_id UUID NOT NULL,
    fecha_inicio TIMESTAMPTZ NOT NULL DEFAULT now(),
    fecha_fin TIMESTAMPTZ,
    notas TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ,
    CONSTRAINT fk_atencion_cita FOREIGN KEY (cita_id) REFERENCES cita(id),
    CONSTRAINT fk_atencion_historia FOREIGN KEY (historia_clinica_id) REFERENCES historia_clinica(id),
    CONSTRAINT fk_atencion_odontologo FOREIGN KEY (odontologo_id) REFERENCES persona(id),
    CONSTRAINT ck_atencion_fechas CHECK (fecha_fin IS NULL OR fecha_fin >= fecha_inicio)
);
CREATE UNIQUE INDEX uq_atencion_cita_active ON atencion (cita_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_atencion_historia_active ON atencion (historia_clinica_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_atencion_en_curso ON atencion (id) WHERE fecha_fin IS NULL AND deleted_at IS NULL;
CREATE TRIGGER trg_atencion_updated BEFORE UPDATE ON atencion
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE enfermedad_actual (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v7(),
    atencion_id UUID NOT NULL,
    motivo_consulta TEXT NOT NULL,
    tiempo_enfermedad VARCHAR(100) NOT NULL DEFAULT '',
    signos_sintomas TEXT NOT NULL DEFAULT '',
    funciones_biologicas TEXT NOT NULL DEFAULT '',
    expectativas_tratamiento TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ,
    CONSTRAINT fk_enfermedad_atencion FOREIGN KEY (atencion_id) REFERENCES atencion(id)
);
CREATE UNIQUE INDEX uq_enfermedad_atencion_active ON enfermedad_actual (atencion_id) WHERE deleted_at IS NULL;
CREATE TRIGGER trg_enfermedad_updated BEFORE UPDATE ON enfermedad_actual
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE antecedente_personal (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v7(),
    historia_clinica_id UUID NOT NULL,
    descripcion TEXT NOT NULL,
    fecha_registro DATE NOT NULL DEFAULT CURRENT_DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ,
    CONSTRAINT fk_antper_historia FOREIGN KEY (historia_clinica_id) REFERENCES historia_clinica(id)
);
CREATE INDEX idx_antper_historia_active ON antecedente_personal (historia_clinica_id) WHERE deleted_at IS NULL;
CREATE TRIGGER trg_antper_updated BEFORE UPDATE ON antecedente_personal
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE antecedente_familiar (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v7(),
    historia_clinica_id UUID NOT NULL,
    parentesco_id SMALLINT NOT NULL,
    descripcion TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ,
    CONSTRAINT fk_antfam_historia FOREIGN KEY (historia_clinica_id) REFERENCES historia_clinica(id),
    CONSTRAINT fk_antfam_parentesco FOREIGN KEY (parentesco_id) REFERENCES parentesco(id)
);
CREATE INDEX idx_antfam_historia_active ON antecedente_familiar (historia_clinica_id) WHERE deleted_at IS NULL;
CREATE TRIGGER trg_antfam_updated BEFORE UPDATE ON antecedente_familiar
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE habito (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v7(),
    historia_clinica_id UUID NOT NULL,
    tipo tipo_habito NOT NULL,
    frecuencia frecuencia_habito NOT NULL,
    detalle TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ,
    CONSTRAINT fk_habito_historia FOREIGN KEY (historia_clinica_id) REFERENCES historia_clinica(id)
);
CREATE UNIQUE INDEX uq_habito_historia_tipo_active ON habito (historia_clinica_id, tipo) WHERE deleted_at IS NULL;
CREATE TRIGGER trg_habito_updated BEFORE UPDATE ON habito
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE odontograma (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v7(),
    historia_clinica_id UUID NOT NULL,
    atencion_id UUID NOT NULL,
    fecha TIMESTAMPTZ NOT NULL DEFAULT now(),
    is_inicial BOOLEAN NOT NULL DEFAULT FALSE,
    observaciones TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ,
    CONSTRAINT fk_odonto_historia FOREIGN KEY (historia_clinica_id) REFERENCES historia_clinica(id),
    CONSTRAINT fk_odonto_atencion FOREIGN KEY (atencion_id) REFERENCES atencion(id)
);
CREATE INDEX idx_odonto_historia_active ON odontograma (historia_clinica_id) WHERE deleted_at IS NULL;
CREATE TRIGGER trg_odonto_updated BEFORE UPDATE ON odontograma
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE odontograma_hallazgo (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v7(),
    odontograma_id UUID NOT NULL,
    pieza_id SMALLINT NOT NULL,
    cara_id SMALLINT NOT NULL,
    condicion_id SMALLINT NOT NULL,
    estado estado_hallazgo NOT NULL DEFAULT 'EXISTENTE',
    notas TEXT NOT NULL DEFAULT '',
    is_registrado_voz BOOLEAN NOT NULL DEFAULT FALSE,
    transcripcion_voz TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ,
    CONSTRAINT fk_hallazgo_odonto FOREIGN KEY (odontograma_id) REFERENCES odontograma(id),
    CONSTRAINT fk_hallazgo_pieza FOREIGN KEY (pieza_id) REFERENCES pieza_dental(id),
    CONSTRAINT fk_hallazgo_cara FOREIGN KEY (cara_id) REFERENCES cara_dental(id),
    CONSTRAINT fk_hallazgo_condicion FOREIGN KEY (condicion_id) REFERENCES condicion_dental(id)
);
CREATE INDEX idx_hallazgo_odonto_active ON odontograma_hallazgo (odontograma_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_hallazgo_pieza_active ON odontograma_hallazgo (pieza_id) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX uq_hallazgo_unico_active
    ON odontograma_hallazgo (odontograma_id, pieza_id, cara_id, condicion_id, estado)
    WHERE deleted_at IS NULL;
CREATE TRIGGER trg_hallazgo_updated BEFORE UPDATE ON odontograma_hallazgo
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE plan_tratamiento (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v7(),
    atencion_id UUID NOT NULL,
    historia_clinica_id UUID NOT NULL,
    estado estado_plan NOT NULL DEFAULT 'PROPUESTO',
    monto_total NUMERIC(10,2) NOT NULL DEFAULT 0,
    observaciones TEXT NOT NULL DEFAULT '',
    is_documento_impreso BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ,
    CONSTRAINT fk_plan_atencion FOREIGN KEY (atencion_id) REFERENCES atencion(id),
    CONSTRAINT fk_plan_historia FOREIGN KEY (historia_clinica_id) REFERENCES historia_clinica(id),
    CONSTRAINT ck_plan_monto CHECK (monto_total >= 0)
);
CREATE INDEX idx_plan_historia_active ON plan_tratamiento (historia_clinica_id) WHERE deleted_at IS NULL;
CREATE TRIGGER trg_plan_updated BEFORE UPDATE ON plan_tratamiento
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE plan_tratamiento_evento (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v7(),
    plan_tratamiento_id UUID NOT NULL,
    estado_nuevo estado_plan NOT NULL,
    actor_persona_id UUID NOT NULL,
    aceptado_por VARCHAR(200) NOT NULL DEFAULT '',
    notas TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_planev_plan FOREIGN KEY (plan_tratamiento_id) REFERENCES plan_tratamiento(id),
    CONSTRAINT fk_planev_actor FOREIGN KEY (actor_persona_id) REFERENCES persona(id)
);
CREATE INDEX idx_planev_plan ON plan_tratamiento_evento (plan_tratamiento_id);

CREATE TABLE plan_tratamiento_detalle (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v7(),
    plan_tratamiento_id UUID NOT NULL,
    procedimiento_id UUID NOT NULL,
    pieza_id SMALLINT NOT NULL DEFAULT 0,
    cara_id SMALLINT NOT NULL,
    cantidad SMALLINT NOT NULL DEFAULT 1,
    precio_unitario NUMERIC(10,2) NOT NULL DEFAULT 0,
    estado estado_detalle_plan NOT NULL DEFAULT 'PENDIENTE',
    orden SMALLINT NOT NULL DEFAULT 1,
    notas TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ,
    CONSTRAINT fk_pdet_plan FOREIGN KEY (plan_tratamiento_id) REFERENCES plan_tratamiento(id),
    CONSTRAINT fk_pdet_procedimiento FOREIGN KEY (procedimiento_id) REFERENCES procedimiento(id),
    CONSTRAINT fk_pdet_pieza FOREIGN KEY (pieza_id) REFERENCES pieza_dental(id),
    CONSTRAINT fk_pdet_cara FOREIGN KEY (cara_id) REFERENCES cara_dental(id),
    CONSTRAINT ck_pdet_cantidad CHECK (cantidad > 0),
    CONSTRAINT ck_pdet_precio CHECK (precio_unitario >= 0)
);
CREATE INDEX idx_pdet_plan_active ON plan_tratamiento_detalle (plan_tratamiento_id) WHERE deleted_at IS NULL;
CREATE TRIGGER trg_pdet_updated BEFORE UPDATE ON plan_tratamiento_detalle
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE tratamiento_ejecutado (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v7(),
    plan_detalle_id UUID NOT NULL,
    atencion_id UUID NOT NULL,
    odontologo_id UUID NOT NULL,
    fecha_ejecucion TIMESTAMPTZ NOT NULL DEFAULT now(),
    observaciones TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ,
    CONSTRAINT fk_ejec_pdet FOREIGN KEY (plan_detalle_id) REFERENCES plan_tratamiento_detalle(id),
    CONSTRAINT fk_ejec_atencion FOREIGN KEY (atencion_id) REFERENCES atencion(id),
    CONSTRAINT fk_ejec_odontologo FOREIGN KEY (odontologo_id) REFERENCES persona(id)
);
CREATE INDEX idx_ejec_atencion_active ON tratamiento_ejecutado (atencion_id) WHERE deleted_at IS NULL;
CREATE TRIGGER trg_ejec_updated BEFORE UPDATE ON tratamiento_ejecutado
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
