-- =====================================================================
-- V2: Seeds de catálogos
-- =====================================================================

SET search_path TO clinica;

-- =====================================================================
-- sexo (SMALLINT PRIMARY KEY — id explícito)
-- =====================================================================
INSERT INTO sexo (id, codigo, descripcion) VALUES
    (1, 'M', 'Masculino'),
    (2, 'F', 'Femenino');

-- =====================================================================
-- tipo_documento (GENERATED BY DEFAULT AS IDENTITY — omitir id)
-- =====================================================================
INSERT INTO tipo_documento (codigo, descripcion) VALUES
    ('DNI',       'Documento Nacional de Identidad'),
    ('CE',        'Carné de Extranjería'),
    ('PASAPORTE', 'Pasaporte'),
    ('RUC',       'Registro Único de Contribuyentes');

-- =====================================================================
-- estado_civil (GENERATED BY DEFAULT AS IDENTITY — omitir id)
-- =====================================================================
INSERT INTO estado_civil (codigo, descripcion) VALUES
    ('SOLTERO',     'Soltero/a'),
    ('CASADO',      'Casado/a'),
    ('DIVORCIADO',  'Divorciado/a'),
    ('VIUDO',       'Viudo/a'),
    ('CONVIVIENTE', 'Conviviente'),
    ('SEPARADO',    'Separado/a');

-- =====================================================================
-- grado_instruccion (GENERATED BY DEFAULT AS IDENTITY + orden)
-- =====================================================================
INSERT INTO grado_instruccion (codigo, descripcion, orden) VALUES
    ('SIN_INSTRUCCION', 'Sin instrucción', 1),
    ('PRIMARIA',        'Primaria',        2),
    ('SECUNDARIA',      'Secundaria',      3),
    ('TECNICO',         'Técnico',         4),
    ('SUPERIOR',        'Superior',        5),
    ('POSGRADO',        'Posgrado',        6);

-- =====================================================================
-- parentesco (GENERATED BY DEFAULT AS IDENTITY — omitir id)
-- =====================================================================
INSERT INTO parentesco (codigo, descripcion) VALUES
    ('PADRE',   'Padre'),
    ('MADRE',   'Madre'),
    ('HIJO',    'Hijo'),
    ('HIJA',    'Hija'),
    ('ESPOSO',  'Esposo'),
    ('ESPOSA',  'Esposa'),
    ('HERMANO', 'Hermano'),
    ('HERMANA', 'Hermana'),
    ('ABUELO',  'Abuelo'),
    ('ABUELA',  'Abuela'),
    ('TIO',     'Tío'),
    ('TIA',     'Tía'),
    ('PRIMO',   'Primo'),
    ('PRIMA',   'Prima'),
    ('SOBRINO', 'Sobrino'),
    ('SOBRINA', 'Sobrina'),
    ('AMIGO',   'Amigo/a'),
    ('TUTOR',   'Tutor/a'),
    ('OTRO',    'Otro');

-- =====================================================================
-- cara_dental (GENERATED BY DEFAULT AS IDENTITY + abreviatura)
-- =====================================================================
INSERT INTO cara_dental (codigo, descripcion, abreviatura) VALUES
    ('VESTIBULAR', 'Vestibular', 'V'),
    ('PALATINO',   'Palatino',   'P'),
    ('LINGUAL',    'Lingual',    'L'),
    ('MESIAL',     'Mesial',     'M'),
    ('DISTAL',     'Distal',     'D'),
    ('OCLUSAL',    'Oclusal',    'O'),
    ('INCISAL',    'Incisal',    'I'),
    ('NO_APLICA',  'No aplica',  'NA');

-- =====================================================================
-- condicion_dental (GENERATED BY DEFAULT AS IDENTITY + color_hex + requiere_cara)
-- =====================================================================
INSERT INTO condicion_dental (codigo, descripcion, color_hex, requiere_cara) VALUES
    ('CARIES',              'Caries',              '#FF0000', TRUE),
    ('OBTURACION',          'Obturación',          '#0000FF', TRUE),
    ('OBTURACION_TEMPORAL', 'Obturación temporal', '#87CEEB', TRUE),
    ('AUSENTE',             'Pieza ausente',       '#000000', FALSE),
    ('CORONA',              'Corona',              '#FFD700', FALSE),
    ('CORONA_TEMPORAL',     'Corona temporal',     '#F0E68C', FALSE),
    ('PUENTE',              'Puente',              '#FFA500', FALSE),
    ('SELLANTE',            'Sellante',            '#00CC00', TRUE),
    ('ENDODONCIA',          'Endodoncia',          '#333333', FALSE),
    ('IMPLANTE',            'Implante',            '#808080', FALSE),
    ('FRACTURA',            'Fractura',            '#800080', TRUE),
    ('MANCHA_BLANCA',       'Mancha blanca',       '#FFFFFF', TRUE),
    ('PROTESIS_REMOVIBLE',  'Prótesis removible',  '#FF69B4', FALSE);

-- =====================================================================
-- pieza_dental (SMALLINT PRIMARY KEY — id FDI explícito)
-- Sentinel: id=0 (NO_APLICA)
-- Permanentes: cuadrantes 1-4, posiciones 1-8
-- Deciduas:    cuadrantes 5-8, posiciones 1-5
-- =====================================================================
INSERT INTO pieza_dental (id, cuadrante, posicion, nombre, is_deciduo) VALUES
    -- Sentinel
    (0,  0, 0, 'No aplica',                FALSE),
    -- Cuadrante 1 (superior derecho permanente)
    (11, 1, 1, 'Incisivo central',         FALSE),
    (12, 1, 2, 'Incisivo lateral',         FALSE),
    (13, 1, 3, 'Canino',                   FALSE),
    (14, 1, 4, 'Primer premolar',          FALSE),
    (15, 1, 5, 'Segundo premolar',         FALSE),
    (16, 1, 6, 'Primer molar',             FALSE),
    (17, 1, 7, 'Segundo molar',            FALSE),
    (18, 1, 8, 'Tercer molar',             FALSE),
    -- Cuadrante 2 (superior izquierdo permanente)
    (21, 2, 1, 'Incisivo central',         FALSE),
    (22, 2, 2, 'Incisivo lateral',         FALSE),
    (23, 2, 3, 'Canino',                   FALSE),
    (24, 2, 4, 'Primer premolar',          FALSE),
    (25, 2, 5, 'Segundo premolar',         FALSE),
    (26, 2, 6, 'Primer molar',             FALSE),
    (27, 2, 7, 'Segundo molar',            FALSE),
    (28, 2, 8, 'Tercer molar',             FALSE),
    -- Cuadrante 3 (inferior izquierdo permanente)
    (31, 3, 1, 'Incisivo central',         FALSE),
    (32, 3, 2, 'Incisivo lateral',         FALSE),
    (33, 3, 3, 'Canino',                   FALSE),
    (34, 3, 4, 'Primer premolar',          FALSE),
    (35, 3, 5, 'Segundo premolar',         FALSE),
    (36, 3, 6, 'Primer molar',             FALSE),
    (37, 3, 7, 'Segundo molar',            FALSE),
    (38, 3, 8, 'Tercer molar',             FALSE),
    -- Cuadrante 4 (inferior derecho permanente)
    (41, 4, 1, 'Incisivo central',         FALSE),
    (42, 4, 2, 'Incisivo lateral',         FALSE),
    (43, 4, 3, 'Canino',                   FALSE),
    (44, 4, 4, 'Primer premolar',          FALSE),
    (45, 4, 5, 'Segundo premolar',         FALSE),
    (46, 4, 6, 'Primer molar',             FALSE),
    (47, 4, 7, 'Segundo molar',            FALSE),
    (48, 4, 8, 'Tercer molar',             FALSE),
    -- Cuadrante 5 (superior derecho deciduo)
    (51, 5, 1, 'Incisivo central deciduo', TRUE),
    (52, 5, 2, 'Incisivo lateral deciduo', TRUE),
    (53, 5, 3, 'Canino deciduo',           TRUE),
    (54, 5, 4, 'Primer molar deciduo',     TRUE),
    (55, 5, 5, 'Segundo molar deciduo',    TRUE),
    -- Cuadrante 6 (superior izquierdo deciduo)
    (61, 6, 1, 'Incisivo central deciduo', TRUE),
    (62, 6, 2, 'Incisivo lateral deciduo', TRUE),
    (63, 6, 3, 'Canino deciduo',           TRUE),
    (64, 6, 4, 'Primer molar deciduo',     TRUE),
    (65, 6, 5, 'Segundo molar deciduo',    TRUE),
    -- Cuadrante 7 (inferior izquierdo deciduo)
    (71, 7, 1, 'Incisivo central deciduo', TRUE),
    (72, 7, 2, 'Incisivo lateral deciduo', TRUE),
    (73, 7, 3, 'Canino deciduo',           TRUE),
    (74, 7, 4, 'Primer molar deciduo',     TRUE),
    (75, 7, 5, 'Segundo molar deciduo',    TRUE),
    -- Cuadrante 8 (inferior derecho deciduo)
    (81, 8, 1, 'Incisivo central deciduo', TRUE),
    (82, 8, 2, 'Incisivo lateral deciduo', TRUE),
    (83, 8, 3, 'Canino deciduo',           TRUE),
    (84, 8, 4, 'Primer molar deciduo',     TRUE),
    (85, 8, 5, 'Segundo molar deciduo',    TRUE);
